version: '3.8'

services:
  excalidraw:
    build:
      context: .
      dockerfile: excalidraw-complete.Dockerfile
    image: excalidraw-full:gated
    pull_policy: never
    ports:
      - "3002:3002"
    volumes:
      - ./data:/root/data
      - ./excalidraw.db:/root/excalidraw.db:Z
      - ./.env:/root/.env
